%YAML:1.0
methodName: "StereoBM_GPU"
preFilterSize: 5
preFilterCap: 1
SADWindowSize: 15
minDisparity: 0
numberOfDisparities: 64
textureThreshold: 4
uniquenessRatio: 15
speckleWindowSize: 0
speckleRange: 0
disp12MaxDiff: 0
