%YAML:1.0
methodName: "StereoSGBM"
preFilterSize: 5
preFilterCap: 1
SADWindowSize: 5
minDisparity: 0
numberOfDisparities: 16
textureThreshold: 0
uniquenessRatio: 0
speckleWindowSize: 0
speckleRange: 0
disp12MaxDiff: 1
